// 后台动态路由
export const backendRoutes = [
    {
        path: '/admin/dashboard',
        name: 'dashboard/dashboard',
        component: () => import('/@/views/backend/dashboard.vue'),
        meta: { title: '控制台', icon: 'fa fa-dashboard', keepalive: 'dashboard/dashboard', type: 'menu', menu_type: 'tab', addtab: true },
    },
    {
        path: '/admin/auth',
        name: 'auth',
        component: '',
        meta: { title: '权限管理', icon: 'fa fa-group', keepalive: 0, type: null },
        children: [
            {
                path: '/admin/auth/group',
                name: 'auth/group',
                component: () => import('/@/views/backend/auth/group/index.vue'),
                meta: { title: '角色组管理', icon: 'fa fa-group', keepalive: 'auth/group', type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
            {
                path: '/admin/auth/admin',
                name: 'auth/admin',
                component: () => import('/@/views/backend/auth/admin/index.vue'),
                meta: { title: '管理员管理', icon: 'el-icon-UserFilled', keepalive: 'auth/admin', type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
            {
                path: '/admin/auth/menu',
                name: 'auth/menu',
                component: () => import('/@/views/backend/auth/menu/index.vue'),
                meta: { title: '菜单规则管理', icon: 'el-icon-Grid', keepalive: 'auth/menu', type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
            {
                path: '/admin/auth/adminLog',
                name: 'auth/adminLog',
                component: () => import('/@/views/backend/auth/adminLog/index.vue'),
                meta: { title: '管理员日志管理', icon: 'el-icon-List', keepalive: 'auth/adminLog', type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
        ],
    },
    {
        path: '/admin/user',
        name: 'user',
        component: '',
        meta: { title: '会员管理', icon: 'fa fa-drivers-license', keepalive: 0, type: null },
        children: [
            {
                path: '/admin/user/user',
                name: 'user/user',
                component: () => import('/@/views/backend/user/user/index.vue'),
                meta: { title: '会员管理', icon: 'fa fa-user', keepalive: 'user/user', type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
            {
                path: '/admin/user/group',
                name: 'user/group',
                component: () => import('/@/views/backend/user/group/index.vue'),
                meta: { title: '会员分组管理', icon: 'fa fa-group', keepalive: 'user/group', type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
            {
                path: '/admin/user/rule',
                name: 'user/rule',
                component: () => import('/@/views/backend/user/rule/index.vue'),
                meta: { title: '会员规则管理', icon: 'fa fa-th-list', keepalive: 'user/rule', type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
            {
                path: '/admin/user/moneyLog',
                name: 'user/moneyLog',
                component: () => import('/@/views/backend/user/moneyLog/index.vue'),
                meta: { title: '会员余额管理', icon: 'el-icon-Money', keepalive: 0, type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
            {
                path: '/admin/user/scoreLog',
                name: 'user/scoreLog',
                component: () => import('/@/views/backend/user/scoreLog/index.vue'),
                meta: { title: '会员积分管理', icon: 'el-icon-Discount', keepalive: 'user/scoreLog', type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
        ],
    },
    {
        path: '/admin/routine',
        name: 'routine',
        component: '',
        meta: { title: '常规管理', icon: 'fa fa-cogs', keepalive: 0, type: null },
        children: [
            {
                path: '/admin/routine/config',
                name: 'routine/config',
                component: () => import('/@/views/backend/routine/config/index.vue'),
                meta: { title: '系统配置', icon: 'el-icon-Tools', keepalive: 'routine/config', type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
            {
                path: '/admin/routine/attachment',
                name: 'routine/attachment',
                component: () => import('/@/views/backend/routine/attachment/index.vue'),
                meta: { title: '附件管理', icon: 'fa fa-folder', keepalive: 'routine/attachment', type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
            {
                path: '/admin/routine/adminInfo',
                name: 'routine/adminInfo',
                component: () => import('/@/views/backend/routine/adminInfo.vue'),
                meta: { title: '个人资料', icon: 'fa fa-user', keepalive: 'routine/adminInfo', type: 'menu', menu_type: 'tab', addtab: true },
                children: [],
            },
        ],
    },
    {
        path: '/admin/moduleStore',
        name: 'moduleStore/moduleStore',
        component: () => import('/@/views/backend/module/index.vue'),
        meta: { title: '模块市场', icon: 'el-icon-GoodsFilled', keepalive: 'moduleStore/moduleStore', type: 'menu', menu_type: 'tab', addtab: true },
        children: [],
    },
    {
        path: '/admin/security',
        name: 'security',
        component: '',
        meta: { title: '数据安全管理', icon: 'fa fa-shield', keepalive: 0, type: null },
        children: [
            {
                path: '/admin/security/dataRecycleLog',
                name: 'security/dataRecycleLog',
                component: () => import('/@/views/backend/security/dataRecycleLog/index.vue'),
                meta: {
                    title: '数据回收站',
                    icon: 'fa fa-database',
                    keepalive: 'security/dataRecycleLog',
                    type: 'menu',
                    menu_type: 'tab',
                    addtab: true,
                },
                children: [],
            },
            {
                path: '/admin/security/sensitiveDataLog',
                name: 'security/sensitiveDataLog',
                component: () => import('/@/views/backend/security/sensitiveDataLog/index.vue'),
                meta: {
                    title: '敏感数据修改记录',
                    icon: 'fa fa-expeditedssl',
                    keepalive: 'security/sensitiveDataLog',
                    type: 'menu',
                    menu_type: 'tab',
                    addtab: true,
                },
                children: [],
            },
            {
                path: '/admin/security/dataRecycle',
                name: 'security/dataRecycle',
                component: () => import('/@/views/backend/security/dataRecycle/index.vue'),
                meta: {
                    title: '数据回收规则管理',
                    icon: 'fa fa-database',
                    keepalive: 'security/dataRecycle',
                    type: 'menu',
                    menu_type: 'tab',
                    addtab: true,
                },
                children: [],
            },
            {
                path: '/admin/security/sensitiveData',
                name: 'security/sensitiveData',
                component: () => import('/@/views/backend/security/sensitiveData/index.vue'),
                meta: {
                    title: '敏感字段规则管理',
                    icon: 'fa fa-expeditedssl',
                    keepalive: 'security/sensitiveData',
                    type: 'menu',
                    menu_type: 'tab',
                    addtab: true,
                },
                children: [],
            },
        ],
    },
    {
        path: '/admin/crud/crud',
        name: 'crud/crud',
        component: () => import('/@/views/backend/crud/index.vue'),
        meta: { title: 'CRUD代码生成', icon: 'fa fa-code', keepalive: 'crud/crud', type: 'menu', menu_type: 'tab', addtab: true },
        children: [],
    },
]
